OES/oes/index/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.index,name='index'),
]

OES/oes/oes/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include(('users.urls','users'),namespace='users')),
    path('captcha/', include('captcha.urls')),
    path('', include(('index.urls', 'index'), namespace='index')),
    path('course/',include(('courses.urls','course'),namespace='course')),
    path('organization/',include(('organizations.urls','organization'),namespace='organization')),
    path('operation/', include(('operations.urls', 'operation'), namespace='operation')),
    # path('haystack/',include('haystack.urls'))

]

OES/oes/users/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('register/',views.UserRegister,name='register'),
    path('login/',views.UserLogin,name='login'),
    path('active_acount/<int:user_id>',views.Active_Acount,name='active_acount'),
    path('forgetpwd/',views.ForgetPwd,name='forgetpwd'),
    path('usercenterinfo/', views.UserCenterInfo, name='usercenterinfo'),
    path('userfavcourse/', views.UserFavCourse, name='userfavcourse'),
    path('userfavteacher/', views.UserFavTeacher, name='userfavteacher'),
    path('userfavorg/', views.UserFavOrg, name='userfavorg'),
    path('usermymsg/', views.MyMsg, name='usermymsg'),
    path('usermycourse/', views.MyCourse, name='usermycourse'),
    path('userlogout/', views.UserLogout, name='userlogout'),
    path('update/pwd/', views.ResetPwd, name='resetpwd'),
    path('image/upload/', views.UploadHeader, name='uploadheader'),
]

OES/oes/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


from basetables.base import BaseModel
# Create your models here.

class UserProfile(AbstractUser):
    image=models.ImageField(verbose_name='用户头像',upload_to='userprofile/%y/%m/%d/',default='default.png',max_length=200)
    birthday=models.CharField(verbose_name='出生日期',blank=True,null=True,max_length=30)
    gender=models.BooleanField(verbose_name='性别',choices=((1,'男'),(2,'女')),default=1)
    address=models.CharField(verbose_name='地址',max_length=200)
    phone=models.CharField(verbose_name='电话号码',max_length=11)

class UserEmail(BaseModel):
    email = models.CharField(max_length=6,verbose_name='邮件地址')
    emialtype = models.IntegerField(verbose_name='邮件种类',choices=((1,'注册激活'),(2,'密码找回')))
    userid = models.IntegerField(verbose_name='用户的id')
    content = models.CharField(verbose_name='邮件内容',max_length=6)

OES/oes/users/forms.py
from django import forms
from captcha.fields import CaptchaField
class RegisterForm(forms.Form):
    email=forms.EmailField()
    password=forms.CharField()
    captcha=CaptchaField()

class ForgetPwdForm(forms.Form):
    email = forms.EmailField()
    captcha = CaptchaField()


class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

OES/oes/users/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
# Create your views here.
from .forms import RegisterForm,ForgetPwdForm
from .models import UserProfile
from utils.sendemail import SendRegisterInfo
from django.db.models import Q
from django.contrib.auth import logout,login,authenticate
from django.contrib.auth.decorators import login_required
from .forms import UploadFileForm
from django.conf import settings
# Imaginary function to handle an uploaded file.
import sys
import os

def UserLogin(request):
    if request.method == 'GET':
        return render(request,'login.html')
    else:
        username = request.POST.get('username','')
        password = request.POST.get('password','')
        if not all([username,password]):        #不能为空
            msg = '信息不完整'
            context={
                'msg':msg,
            }
            return render(request,'login.html',context=context)
        userlist=UserProfile.objects.filter(Q(email=username)|Q(phone=username))
        if not userlist:
            msg = '用户不存在'
            context={
                'msg':msg,
            }
            return render(request,'login.html',context=context)

        user=userlist[0]
        username=user.username
        user=authenticate(username=username, password=password)     #
        if user:    #表示验证成功
            if not user.is_active:      #表示没有激活
                SendRegisterInfo(user)  #发送激活链接
                return HttpResponse('已经发送激活链接到你的邮箱')
            login(request,user)
            return redirect('index:index')
        else:
            msg = '密码错误'
            context = {
                'msg': msg,
            }
            return render(request, 'login.html', context=context)
        # if userlist[0].password != password:


        # if userlist[0].is_active():
        #     msg = '账户没有激活'
        #     context={
        #         'msg':msg,
        #     }
        #     return render(request,'login.html',context=context)
        # login(request,userlist[0])


def UserRegister(request):
    registerform = RegisterForm()
    if request.method == 'GET':

        context={
            'registerform':registerform,
        }
        return render(request,'register.html',context=context)
    else:
        formdata = RegisterForm(request.POST)
        if formdata.is_valid():     #表示输入合法
            email = formdata.cleaned_data['email']
            password = formdata.cleaned_data['password']
            emial_list=UserProfile.objects.filter(email=email)
            if emial_list:      #表示已经存在注册的emial
                msg = 'emial已经被注册'
                context = {
                    'msg': msg,
                    'registerform': registerform,
                }
            else:
                user=UserProfile.objects.create_user(username=email,email=email,password=password)
                user.is_active=0
                user.save()
                SendRegisterInfo(user)
                return HttpResponse('register success')
        else:
            msg='输入不合理'
            context={
                'msg':msg,
                'registerform': registerform,
            }
        return render(request,'register.html',context=context)


def Active_Acount(request,user_id):
    user_list=UserProfile.objects.filter(id=user_id)
    if user_list:
        user_list[0].is_active=1
        user_list[0].save()
        return HttpResponse('激活成功')
    else:
        return HttpResponse('出错')


def ForgetPwd(request):

    if request.method == 'GET':
        form = ForgetPwdForm()
        context={
            'captcha':form,
        }
        return render(request,'forgetpwd.html',context=context)
    else:
        email = request.POST.get('email','')
        if not email:
            context={
                'msg':'不存在这个账户'
            }
            return render(request,'forgetpwd.html',context=context)
        form = ForgetPwdForm(request.POST)
        if not form.is_valid(): #判断是否有效
            context={
                'msg':'输入错误'
            }
            return render(request,'forgetpwd.html',context=context)


@login_required
def UploadHeader(request):
    user = request.user
    with open(str(user.email)+'.png', 'wb') as destination:
        for chunk in request.FILES['file'].chunks():
            destination.write(chunk)

    user.image = '/static/media/header/'+str(user.email)+'.png'
    user.save()
    return redirect('users:usercenterinfo')

@login_required
def UserCenterInfo(request):
    user = request.user         #得到登录的用户
    if request.method == 'GET':
        context={
            'username' : user.username,
            'birthday' : user.birthday,
            'gender' :  user.gender,
            'address' : user.address,
            'phone' : user.phone,
            'email' : user.email,
            'image' : user.image,
        }
        return render(request,'user/usercenter-info.html',context=context)
    else:
        username = request.POST['nick_name']
        birthday = request.POST['birday']
        gender = request.POST['gender']
        address = request.POST['address']
        phone = request.POST['mobile']
        print('hfdfd')
        user.username = username
        user.birthday = birthday
        user.gender = gender
        user.address = address
        user.phone = phone

        user.save()

        return redirect('users:usercenterinfo')

@login_required
def ResetPwd(request):
    user = request.user
    if request.method == 'GET':
        return HttpResponse('error')
    else:
        pwd1 = request.POST['password1']
        pwd2 = request.POST['password2']
        if pwd1 != pwd2:
            return HttpResponse('密码不一致')
        user.set_password(pwd2)

        user.save()
        logout(request)
        return redirect('users:login')


@login_required
def UserFavCourse(request):
    if request.method == 'GET':
        return render(request,'user/usercenter-fav-course.html')


@login_required
def UserFavTeacher(request):
    if request.method == 'GET':
        return render(request,'user/usercenter-fav-teacher.html')

@login_required
def UserFavOrg(request):
    if request.method == 'GET':
        return render(request,'user/usercenter-fav-org.html')

@login_required
def MyMsg(request):
    if request.method == 'GET':
        return render(request,'user/usercenter-message.html')

@login_required
def MyCourse(request):
    if request.method == 'GET':
        return render(request,'user/usercenter-mycourse.html')


@login_required
def UserLogout(request):
    logout(request)
    return redirect('index:index')

OES/oes/templates/user/userbase.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}个人信息- 谷粒教育网{% endblock %}</title>

    {% block topfile %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/lq.datetimepick.css' %}"/>
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    {% endblock %}
</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header2 header">
 			<div class="top">
				<div class="wp">
					<div class="fl"><p>服务电话：<b>88888888</b></p></div>
					<!--登录后跳转-->


                        <div class="personal">
                            <dl class="user fr">
                                <dd>{{request.user.username}}<img class="down fr" src="{{request.user.image}}"/></dd>
                                <dt><img width="20" height="20" src="{{request.user.image}}"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="{% static 'images/touxiang.jpg' %}"/></dt>
	                                <dd>
	                                    <h2>django</h2>
	                                    <p>{{request.user.username}}</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="{% url 'users:usercenterinfo' %}">进入个人中心</a>
	                                <a class="fr" href="{% url 'users:userlogout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                        <a href="usercenter-message.html">
                            <div class="msg-num"><span id="MsgNum">0</span></div>
                        </a>


				</div>
			</div>

    <div class="middle">
        <div class="wp">
            <a href="{% url 'index:index' %}"><img class="fl" src="{% static 'images/logo1.png' %}"/></a>
            <h1>我的谷粒教育网</h1>
        </div>
    </div>
			</div>
    </header>
</section>



{% block content %}

{% endblock %}


<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>





{% block bottomfile %}
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.upload.js' %}" type='text/javascript'></script>
<script src="{% static 'js/validate.js' %}" type="text/javascript"></script>
<script src="{% static 'js/deco-user.js' %}"></script>
{% endblock %}

{% block script %}
<script type="text/javascript">
    $('.jsDeleteFav_course').on('click', function(){
        var _this = $(this),
            favid = _this.attr('data-favid');
        alert(favid)
        $.ajax({
                cache: false,
                type: "POST",
                url: "/org/add_fav/",
                data: {
                    fav_type: 1,
                    fav_id: favid,
                    csrfmiddlewaretoken: '799Y6iPeEDNSGvrTu3noBrO4MBLv6enY'
                },
                async: true,
                success: function(data) {
                    Dml.fun.winReload();
                }
            });
    });

    $('.jsDeleteFav_teacher').on('click', function(){
            var _this = $(this),
                favid = _this.attr('data-favid');
            $.ajax({
                    cache: false,
                    type: "POST",
                    url: "/org/add_fav/",
                    data: {
                        fav_type: 3,
                        fav_id: favid,
                        csrfmiddlewaretoken: '799Y6iPeEDNSGvrTu3noBrO4MBLv6enY'
                    },
                    async: true,
                    success: function(data) {
                        Dml.fun.winReload();
                    }
                });
        });


    $('.jsDeleteFav_org').on('click', function(){
            var _this = $(this),
                favid = _this.attr('data-favid');
            $.ajax({
                    cache: false,
                    type: "POST",
                    url: "/org/add_fav/",
                    data: {
                        fav_type: 2,
                        fav_id: favid,
                        csrfmiddlewaretoken: '799Y6iPeEDNSGvrTu3noBrO4MBLv6enY'
                    },
                    async: true,
                    success: function(data) {
                        Dml.fun.winReload();
                    }
                });
        });
</script>


<script>
        var shareUrl = '',
            shareText = '',
            shareDesc = '',
            shareComment = '';
        $(function () {
            $(".bdsharebuttonbox a").mouseover(function () {
                var type = $(this).attr('data-cmd'),
                    $parent = $(this).parent('.bdsharebuttonbox'),
                    fxurl = $parent.attr('data-url'),
                    fxtext = $parent.attr('data-text'),
                    fxdesc = $parent.attr('data-desc'),
                    fxcomment = $parent.attr('data-comment');
                switch (type){
                    case 'tsina':
                    case 'tqq':
                    case 'renren':
                            shareUrl = fxurl;
                            shareText = fxdesc;
                            shareDesc = '';
                            shareComment = '';
                        break;
                    default :
                            shareUrl = fxurl;
                            shareText = fxtext;
                            shareDesc = fxdesc;
                            shareComment = fxcomment;
                        break;
                }
            });
        });
        function SetShareUrl(cmd, config) {
            if (shareUrl) {
                config.bdUrl = "" + shareUrl;
            }
            if(shareText){
                config.bdText = shareText;
            }
            if(shareDesc){
                config.bdDesc = shareDesc;
            }
            if(shareComment){
                config.bdComment = shareComment;
            }

            return config;
        }
        window._bd_share_config = {
            "common": {
                "onBeforeClick":SetShareUrl,
                "bdPic":"",
                "bdMini":"2",
                "searchPic":"1",
                "bdMiniList":false
            },
            "share": {
                "bdSize":"16"
            }
        };
    with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com../api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];
</script>
{% endblock %}
</body>
</html>

OES/oes/templates/user/usercenter-fav-course.html
{% extends 'user/userbase.html' %}
{% load static %}
	{% block title %}我的收藏- 谷粒教育网{% endblock %}



{% block content %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="index.html">首页</a>></li>
                <li><a href="/user/home/">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>

<section>
	<div class="wp list personal_list">

	<div class="left">
        <ul>
            <li><a href="{% url 'users:usercenterinfo' %}">个人资料</a></li>
            <li ><a href="{% url 'users:usermycourse' %}">我的课程</a></li>
            <li  class="active2"><a href="{% url 'users:userfavcourse' %}">我的收藏</a></li>
            <li >
                <a href="{% url 'users:usermymsg' %}" style="position: relative;">
                    我的消息
                </a>
            </li>
        </ul>
	</div>

    
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'users:userfavorg' %}">课程机构</a> </li>
                        <li><a href="{% url 'users:userfavteacher' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'users:userfavcourse' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        
                        <div class="module1_5 box">
                            <a href="course-detail.html">
                                <img width="214" height="190" src="../images/mysql.jpg"/>
                            </a>
                            <div class="des">
                                <a href="course-detail.html"><h2>mysql基础</h2></a>
                                <span class="fl">时长：<i class="key">55</i></span>
                                <span class="fr">学习人数：0</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">尚硅谷</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="12"></span>
                            </div>
                        </div>
                        
                        <div class="module1_5 box">
                            <a href="course-detail.html">
                                <img width="214" height="190" src="../images/oracle.jpg"/>
                            </a>
                            <div class="des">
                                <a href="course-detail.html"><h2>数据库oracle全讲</h2></a>
                                <span class="fl">时长：<i class="key">30</i></span>
                                <span class="fr">学习人数：2</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">谷粒教育网</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="13"></span>
                            </div>
                        </div>
                        

                    </div>
                </div>
            </div>
        </div>


	</div>
</section>


<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>

{% endblock %}

OES/oes/templates/user/usercenter-fav-org.html
{% extends 'user/userbase.html' %}
{% load static %}
{% block title %}我的收藏- 谷粒教育网{% endblock %}

{% block content %}

    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="index.html">首页</a>></li>
                <li><a href="/user/home/">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>

<section>
	<div class="wp list personal_list">
	<div class="left">
        <ul>
            <li><a href="{% url 'users:usercenterinfo' %}">个人资料</a></li>
            <li  ><a href="{% url 'users:usermycourse' %}">我的课程</a></li>
            <li class="active2"><a href="{% url 'users:userfavcourse' %}">我的收藏</a></li>
            <li >
                <a href="{% url 'users:usermymsg' %}" style="position: relative;">
                    我的消息
                </a>
            </li>
        </ul>
	</div>

    
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                    <ul class="tab_header messagehead">
                        <li class="active"><a href="{% url 'users:userfavorg' %}">课程机构</a> </li>
                        <li><a href="{% url 'users:userfavteacher' %}">授课教师 </a></li>
                        <li><a href="{% url 'users:userfavcourse' %}">公开课程</a></li>
                    </ul>
                    </ul>
                </div>
                <div class="messagelist">
                    
                    <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="org-detail-homepage.html">
                                    <img width="160" height="90" src="../images/org.png"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="org-detail-homepage.html">尚硅谷</a></h1>
                                <div class="pic fl" style="width:auto;">

                                    <img src="../images/authentication.png"/>


                                    <img src="../images/gold.png"/>

                                </div>
                                <span class="c8 clear">北京市</span>
                                <div class="delete jsDeleteFav_org" data-favid="1"></div>
                            </dd>
                        </dl>
                    </div>

                </div>
            </div>
        </div>


	</div>
</section>
{% endblock %}

OES/oes/templates/user/usercenter-fav-teacher.html
{% extends 'user/userbase.html' %}
{% load static %}
{% block title %}我的收藏- 谷粒教育网{% endblock %}

{% block content %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="index.html">首页</a>></li>
                <li><a href="/user/home/">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>

<section>
	<div class="wp list personal_list">
	<div class="left">
        <ul>
            <li><a href="usercenter-info.html">个人资料</a></li>
            <li ><a href="usercenter-mycourse.html">我的课程</a></li>
            <li  class="active2"><a href="usercenter-fav-course.html">我的收藏</a></li>
            <li >
                <a href="usercenter-message.html" style="position: relative;">
                    我的消息
                </a>
            </li>
        </ul>
	</div>

    
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'users:userfavorg' %}">课程机构</a> </li>
                        <li class="active"><a href="{% url 'users:userfavteacher' %}">授课教师 </a></li>
                        <li><a href="{% url 'users:userfavcourse' %}">公开课程</a></li>
                    </ul>
                    </ul>
                </div>
                <div class="messagelist">
                    
                    <div class=" butler_list butler-fav-box">
                        <dl class="des users">
                            <dt>
                                <a href="/org/teacher/detail/1/">
                                    <img width="100" height="100" src="../images/touxiang.jpg"/>
                                </a>
                            </dt>
                            <dd>
                                <h1>
                                    <a href="/org/teacher/detail/1/">
                                        weesmile<span class="key">认证教师</span>
                                    </a>
                                </h1>
                                <ul class="cont clearfix">
                                    <li class="time">工作年限：<span>5年</span></li>
                                    <li class="c7">课程数：<span>2</span></li>
                                </ul>
                                <ul class="cont clearfix">
                                    <li class="time">工作公司：<span>xxx</span></li>
                                    <li class="c7">公司职位：<span>xxx</span></li>
                                </ul>
                            </dd>
                            <div class="delete jsDeleteFav_teacher" data-favid="1"></div>
                        </dl>
                    </div>
                    
                    <div class=" butler_list butler-fav-box">
                        <dl class="des users">
                            <dt>
                                <a href="/org/teacher/detail/2/">
                                    <img width="100" height="100" src="../images/touxiang.jpg"/>
                                </a>
                            </dt>
                            <dd>
                                <h1>
                                    <a href="/org/teacher/detail/2/">
                                        还是weesmile<span class="key">认证教师</span>
                                    </a>
                                </h1>
                                <ul class="cont clearfix">
                                    <li class="time">工作年限：<span>5年</span></li>
                                    <li class="c7">课程数：<span>1</span></li>
                                </ul>
                                <ul class="cont clearfix">
                                    <li class="time">工作公司：<span>xxx</span></li>
                                    <li class="c7">公司职位：<span>xxx</span></li>
                                </ul>
                            </dd>
                            <div class="delete jsDeleteFav_teacher" data-favid="2"></div>
                        </dl>
                    </div>
                    
                </div>
            </div>
        </div>


	</div>
</section>


{% endblock %}

OES/oes/templates/user/usercenter-message.html
{% extends 'user/userbase.html' %}
{% load static %}
{% block title %}我的消息- 谷粒教育网{% endblock %}




{% block content %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="index.html">首页</a>></li>
                <li><a href="/user/home/">个人中心</a>></li>
                <li>我的消息</li>
            </ul>
        </div>
    </section>

<section>
	<div class="wp list personal_list">
	<div class="left">
        <ul>
            <li><a href="{% url 'users:usercenterinfo' %}">个人资料</a></li>
            <li ><a href="{% url 'users:usermycourse' %}">我的课程</a></li>
            <li ><a href="{% url 'users:userfavcourse' %}">我的收藏</a></li>
            <li  class="active2">
                <a href="{% url 'users:usermymsg' %}" style="position: relative;">
                    我的消息
                </a>
            </li>
        </ul>
	</div>

    
    <div class="right" >
		<div class="personal_des Releasecont">
			<div class="head">
				<h1>我的消息</h1>
			</div>

		</div>
		<div class="personal_des permessage">
			<div class="head">
				<ul class="tab_header messagehead">
					<li class="active"><a href="/user/message/">个人消息</a> </li>
				</ul>


			</div>
			<div class="messagelist">
                
                    <div class="messages">
                        <div class="fr">
                            <div class="top"><span class="fl time">2018年5月6日 23:49</span><span class="fr btn foldbtn"></span></div>
                            <p>
                                欢迎注册
                            </p>
                        </div>
                    </div>
                


			</div>


			<div class="pageturn pagerright">
                <ul class="pagelist">
                

                
                    
                        
                            <li class="active"><a href="?page=1">1</a></li>
                        
                    
                
                

            </ul>
            </div>
		</div>

	</div>


	</div>
</section>

{% endblock %}