OES/oes/courses/urls.py
from django.urls import path
from . import views
from haystack.views import SearchView
urlpatterns=[
    path('courselist/',views.CourseList,name='courselist'),
    path('coursedetail/<int:course_id>/',views.CourseDetail,name='coursedetail'),
    path('coursechapter/<int:course_id>/',views.CourseChapter,name='coursechapter'),
    path('video/<int:video_id>/',views.VideoOpen,name='video'),
    # path('search/', SearchView(), name='haystack_search'),

]

OES/oes/oes/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include(('users.urls','users'),namespace='users')),
    path('captcha/', include('captcha.urls')),
    path('', include(('index.urls', 'index'), namespace='index')),
    path('course/',include(('courses.urls','course'),namespace='course')),
    path('organization/',include(('organizations.urls','organization'),namespace='organization')),
    path('operation/', include(('operations.urls', 'operation'), namespace='operation')),
    # path('haystack/',include('haystack.urls'))

]

OES/oes/organizations/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('teacherlist/',views.TeacherList,name='teacherlist'),
    path('teacherdetail/<int:teacher_id>',views.TeacherDetail,name='teacherdetail'),
    path('organizationlist/',views.OrganizationList,name='organizationlist'),
    path('organizationdetailcourse/<int:org_id>',views.OrganizationDetailCourse,name='organizationdetailcourse'),
    path('organizationdetailpagehome/<int:org_id>', views.OrganizationDetailPagehome, name='organizationdetailpagehome'),
    path('organizationdetaildesc/<int:org_id>', views.OrganizationDetailDes, name='organizationdetaildesc'),
    path('organizationdetailteacher/<int:org_id>', views.OrganizationDetailTeacher, name='organizationdetailteacher'),
]

OES/oes/templates/course/course-detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}公开课列表 - 谷粒教育网{% endblock %}




{% block content %}
    <section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="index.html">首页</a>></li>
                <li><a href="course-list.html">公开课程</a>></li>
				<li>课程详情</li>

			</ul>
		</div>
	</div>
</section>


    <section>
	<div class="wp">
		<div class="groupPurchase_detail detail">
			<div class="toppro">
				<div class="left">
					<div class="picbox">
						<div class="tb-booth tb-pic">
							<img width="440" height="445" src="/static/media/{{course.image}}" class="jqzoom" />
						</div>

					</div>
					<div class="des">
						<h1 title="mysql基础">{{course.name}}</h1>
						<span class="key">{{course.introduce}}</span>
						<div class="prize">
							<span class="fl">难度：<i class="key">{% if course.grade == 1 %}初级{% elif course.grade == 2 %}中级{% else %}高级{% endif %}</i></span>
							<span class="fr">学习人数：{{course.learn_num}}</span>
						</div>
						<ul class="parameter">
							<li><span class="pram word3">时&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;长：</span><span>{{course.time}}</span></li>
                            <li><span class="pram word3">章&nbsp;节&nbsp;数：</span><span>{{course.chapter_num}}</span></li>
                            <li><span class="pram word3">课程类别：</span><span title="">{{course.course_category}}</span></li>
							<li class="piclist"><span class="pram word4">学习用户：</span>

                                    <span class="pic"><img width="40" height="40" src="../images/touxiang.jpg"/></span>

							</li>
						</ul>
						<div class="btns">
							<div class="btn colectgroupbtn"  id="jsLeftBtn">
                                  收藏
                            </div>
                                <div class="buy btn"><a style="color: white" href="{% url 'course:coursechapter' course.id %}">开始学习</a></div>
						</div>
					</div>
				</div>



				<div class="right">
					<div class="head">
						<h1>授课机构</h1>
						<p>世界名校，课程权威</p>
					</div>
					<div class="pic">
                        <a href="{% url 'organization:organizationdetailpagehome' org.id %}">
                            <img width="150" height="80" src="/static/media/{{org.image}}"/>
                        </a>
                    </div>
					<a href="/company/14/">
                        <h2 class="center" title="尚硅谷">{{org.name}}</h2>
                    </a>
					<div class="btn  notlogin
					     "data-favid="14" id="jsRightBtn">
                         已收藏
                    </div>
					<div class="clear">
						<ul>
                            <li>
                                <span>课 &nbsp;程&nbsp; 数：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   {{org.course_num}}</span>
                            </li>
                            <li>
                                <span>教 &nbsp;师&nbsp; 数：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  {{org.teacher_num}}</span>
                            </li>
							<li>所在地区：&nbsp;&nbsp;{{org.city.city}}</li>
							<li>认&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;证&nbsp;:
                                &nbsp;&nbsp;
								    <img title="金牌机构", src="{% static 'images/gold.png' %}"/>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
    <section>
	<div class="wp">
		<div class="list groupPurchase_detail_pro">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li class="active">课程详情</li>

					</ul>

				</div>
				<div class="tab_cont tab_cont1">
                    				{{ course.detail }}
					<p></p>

				</div>
				<div class="tab_cont tab_cont2" >
					<div class="comment">
						<div class="comenlist">

	                    </div>
					</div>
				</div>
			</div>
			<div class="right layout">
				<div class="head">相关课程推荐</div>
                <div class="group_recommend">

                        <dl>
                            <dt>
                                <a target="_blank" href="">
                                    <img width="240" height="220" class="scrollLoading" src="../images/mysql.jpg"/>
                                </a>
                            </dt>
                            <dd>
                                <a target="_blank" href=""><h2> mysql高级</h2></a>
                                <span class="fl">学习时长：<i class="key">0</i></span>
                            </dd>
                        </dl>



                </div>
			</div>
		</div>
	</div>
</section>

{% endblock %}

OES/oes/templates/course/course-list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}公开课列表 - 谷粒教育网{% endblock %}

{% block content %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="index.html">首页</a>></li>
                <li>公开课</li>
            </ul>
        </div>
    </section>


    <section>
	<div class="wp">
		<div class="list" style="margin-top:0;">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li class="active"><a href="?sort=">最新 </a></li>
						<li ><a href="?sort=hot">最热门</a></li>
						<li ><a href="?sort=students">参与人数</a></li>
					</ul>
				</div>
                <div id="inWindow">
                    <div class="tab_cont " id="content">
					<div class="group_list">

                            {% for course in course_list %}
                            <div class="box">
                                <a href="{% url 'course:coursedetail' course.id %}">
                                    <img width="280" height="350" class="scrollLoading" src="/static/media/{{course.image}}"/>
                                </a>
                                <div class="des">
                                    <a href="course-detail.html">
                                        <h2>{{course.name}}</h2>
                                    </a>
                                    <span class="fl">时长：<i class="key">{{course.time}}</i></span>
                                    <span class="fr">学习人数：{{course.learn_num}}&nbsp;&nbsp;</span>
                                </div>
                                <div class="bottom">
                                    <a href="course-detail.html"><span class="fl">来自{{course.teacher.organization.name}}</span></a>
                                    <span class="star fr  notlogin
                                        " data-favid="15">
                                        {{course.fav_num}}
                                    </span>
                                </div>
                            </div>
                            {% endfor %}

					</div>
                    <div class="pageturn">
                        <ul class="pagelist">
                            

                                {% if last != 0 %}
                                <li class="long"><a href="?page={{last}}">上一页</a></li>
                                {% endif %}
                                 {% for pagei in page_list %}
                                    {% if pagei == page %}
                                        <li class="active"><a href="?page={{pagei}}">{{pagei}}</a></li>
                                    {% else %}
                                        <li class=""><a href="?page={{pagei}}">{{pagei}}</a></li>
                                    {% endif %}
                                {% endfor %}
                                {% if next != 0 %}
                                <li class="long"><a href="?page={{next}}">下一页</a></li>
                                {% endif %}

                        </ul>
                    </div>
				</div>
                </div>
			</div>
			<div class="right layout">
				<div class="head">热门课程推荐</div>
				<div class="group_recommend">

					{% for course in hotcourse_list %}
                    <dl>
						<dt>
							<a target="_blank" href="{% url 'course:coursedetail' course.id %}">
								<img width="240" height="220" class="scrollLoading" src="/static/media/{{course.image}}"/>
							</a>
						</dt>
						<dd>
							<a target="_blank" href=""><h2> {{course.name}}</h2></a>
							<span class="fl">难度：<i class="key">{% if course.grade == 1 %}初级{% elif course.grade == 2 %}中级{% else %}高级{% endif %}</i></span>
						</dd>
					</dl>
					{% endfor %}

                    


				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}

OES/oes/templates/course/course-video.html
{% extends 'base.html' %}
{% load static %}
{% block title %}公开课视频信息 - 谷粒教育网{% endblock %}

{% block topfile %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/common-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/course/learn-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/aui.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
     <link rel="stylesheet" type="text/css" href="{% static 'css/guli/course/common-less.css' %}">

    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
{% endblock %}
{% block content %}

    <section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="index.html">首页</a>></li>
                <li><a href="course-list.html">公开课程</a>></li>
				<li><a href="course-detail.html">课程详情</a>></li>
                <li>章节信息</li>
			</ul>
		</div>
	</div>
</section>


    <div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{course.name}}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{% if course.grade == 1 %}初级{% elif course.grade == 2 %}中级{% else %}高级{% endif %}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{course.time}}分钟</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{course.learn_num}}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
        <div class="content-wrap clearfix">
            <div class="content">
                <div class="mod-tab-menu">
                    <ul class="course-menu clearfix">
                        <li><a class="ui-tabs-active active" id="learnOn"  href="course-video.html"><span>章节</span></a></li>
                        <li><a id="commentOn" class="" href="course-comment.html"><span>评论</span></a></li>
                    </ul>
                </div>
                <div id="notice" class="clearfix">
                    <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">Spring的文档以及相关的jar文件已上传</a> </div>
                </div>

                <div class="mod-chapters">
                    {% for chapter in chapter_list %}
                    <div class="chapter chapter-active" >
                        <h3>
                            <strong><i class="state-expand"></i>第{{forloop.counter}}章 {{chapter.name}}</strong>
                        </h3>
                        <ul class="video">
                            {% for video in chapter.video_list %}
                            <li>
                                <a target="_blank" href="/course/video/{{video.id}}/" class="J-media-item studyvideo"> {{video.name}} ({{video.time}})
                                    <i class="study-state"></i>
                                </a>
                            </li>
                            {% endfor %}
                            
                        </ul>
                    </div>
                    {% endfor %}
                    

                </div>

            </div>
            <div class="aside r">
                <div class="bd">

                    <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                            {% for source in source_list %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{source.name}}</span>
                                <a href="/static/media/{{source.file}}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                            {% endfor %}
                            
                        </ul>
                    </div>
                    <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="{% url 'organization:teacherdetail' teacher.id %}" target="_blank">
                                <img src="{% static 'images/touxiang.jpg' %}" width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="{% url 'organization:teacherdetail' teacher.id %}" target="_blank">{{teacher.name}}</a>
        </span>
                            <span class="job">xxx</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{course.should_kown}}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{course.learn_kg}}</dd>
                            </dl>
                        </div>
                    </div>


                    <div class="cp-other-learned  js-comp-tabs">
                        <div class="cp-header clearfix">
                            <h2 class="cp-tit l">该课的同学还学过</h2>
                        </div>
                        <div class="cp-body">
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                <!-- img 200 x 112 -->
                                <ul class="other-list">
                                    
                                    <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="{% static 'images/mysql.jpg' %}" >
                                            <span class="name autowrap">mysql高级</span>
                                        </a>
                                    </li>
                                    
                                    <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="{% static 'images/oracle.jpg' %}">
                                            <span class="name autowrap">oracle全讲</span>
                                        </a>
                                    </li>

                                </ul>
                            </div>
                       
                        </div>
                    </div>

                </div>    </div>
        </div>
        <div class="clear"></div>

    </div>

</div>
</div>

{% endblock %}

OES/oes/templates/course/video.html
<!DOCTYPE html>
<html>
<head> 
<meta charset="utf-8"> 
<title>视频播放</title> 
  <style>
  *{
    margin:0;
    padding:0;
  }
  body{
    background-color:grey;
  }
    .container{
      width:1200px;
      height:700px;
      margin:0 auto;
    }
    video{
      height:100%;
      width:100%;
    }
  </style>
</head>
<body>


<div class="container">
<video controls>
  <source src="/static/media/{{url}}" type="video/mp4">
</video>
</div>


</body>
</html>