OES/oes/courses/urls.py
from django.urls import path
from . import views
from haystack.views import SearchView
urlpatterns=[
    path('courselist/',views.CourseList,name='courselist'),
    path('coursedetail/<int:course_id>/',views.CourseDetail,name='coursedetail'),
    path('coursechapter/<int:course_id>/',views.CourseChapter,name='coursechapter'),
    path('video/<int:video_id>/',views.VideoOpen,name='video'),
    # path('search/', SearchView(), name='haystack_search'),

]

OES/oes/index/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.index,name='index'),
]

OES/oes/oes/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include(('users.urls','users'),namespace='users')),
    path('captcha/', include('captcha.urls')),
    path('', include(('index.urls', 'index'), namespace='index')),
    path('course/',include(('courses.urls','course'),namespace='course')),
    path('organization/',include(('organizations.urls','organization'),namespace='organization')),
    path('operation/', include(('operations.urls', 'operation'), namespace='operation')),
    # path('haystack/',include('haystack.urls'))

]

OES/oes/organizations/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('teacherlist/',views.TeacherList,name='teacherlist'),
    path('teacherdetail/<int:teacher_id>',views.TeacherDetail,name='teacherdetail'),
    path('organizationlist/',views.OrganizationList,name='organizationlist'),
    path('organizationdetailcourse/<int:org_id>',views.OrganizationDetailCourse,name='organizationdetailcourse'),
    path('organizationdetailpagehome/<int:org_id>', views.OrganizationDetailPagehome, name='organizationdetailpagehome'),
    path('organizationdetaildesc/<int:org_id>', views.OrganizationDetailDes, name='organizationdetaildesc'),
    path('organizationdetailteacher/<int:org_id>', views.OrganizationDetailTeacher, name='organizationdetailteacher'),
]

OES/oes/users/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('register/',views.UserRegister,name='register'),
    path('login/',views.UserLogin,name='login'),
    path('active_acount/<int:user_id>',views.Active_Acount,name='active_acount'),
    path('forgetpwd/',views.ForgetPwd,name='forgetpwd'),
    path('usercenterinfo/', views.UserCenterInfo, name='usercenterinfo'),
    path('userfavcourse/', views.UserFavCourse, name='userfavcourse'),
    path('userfavteacher/', views.UserFavTeacher, name='userfavteacher'),
    path('userfavorg/', views.UserFavOrg, name='userfavorg'),
    path('usermymsg/', views.MyMsg, name='usermymsg'),
    path('usermycourse/', views.MyCourse, name='usermycourse'),
    path('userlogout/', views.UserLogout, name='userlogout'),
    path('update/pwd/', views.ResetPwd, name='resetpwd'),
    path('image/upload/', views.UploadHeader, name='uploadheader'),
]

OES/oes/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}课程机构列表 - 谷粒教育{% endblock %}</title>
    {% block topfile %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    {% endblock %}

</head>
<body>
<section class="headerwrap ">
    <header>
		<div  class=" header">
 			<div class="top">
				<div class="wp">
					<div class="fl"><p>服务电话：<b>8888888</b></p></div>
					<!--登录后跳转-->

                        {% if not request.user.is_authenticated %}
                         <a style="color:white" class="fr registerbtn" href="{% url 'users:register' %}">注册</a>
                         <a style="color:white" class="fr loginbtn" href="{% url 'users:login' %}">登录</a>
						{% else %}
						<div class="personal">
                            <dl class="user fr">
                                <dd>{{ request.user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{{request.user.image}}"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="{{request.user.image}}"/></dt>
	                                <dd>
	                                    <h2>django</h2>
	                                    <p>{{ request.user.username }}</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="{% url 'users:usercenterinfo' %}">进入个人中心</a>
	                                <a class="fr" href="{% url 'users:userlogout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                        {% endif %}

				</div>
			</div>

            <div class="middle">
                <div class="wp">
                    <a href="index.html"><img class="fl" src="{% static 'images/logo1.png' %}"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课老师</li>
                            </ul>
                        </div>
						<form action="" method="get">

						</form>
                        <input id="search_keywords" class="fl" type="text" value="" name="q" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                    </div>
                </div>
            </div>
            
            
			<nav>
				<div class="nav">
					<div class="wp">
						<ul>
							<li {% if flag == 'index' %}class="active"{% endif %} ><a href="{% url 'index:index' %}">首页</a></li>
							<li {% if flag == 'course' %}class="active"{% endif %}>
								<a href="{% url 'course:courselist' %}">
									公开课<img class="hot" src="{% static 'images/nav_hot.png' %}">
								</a>
							</li>
							<li {% if flag == 'teacher' %}class="active"{% endif %}>
								<a href="{% url 'organization:teacherlist' %}">授课教师</a>
							</li >
							<li {% if flag == 'organization' %}class="active"{% endif %}><a href="{% url 'organization:organizationlist' %}">授课机构</a></li>
						</ul>
					</div>
				</div>
			</nav>
            
			</div>
    </header>
</section>


{% block content %}
{% endblock %}
<footer>
		<div class="footer">
			<div class="wp">
				<ul class="cont">
					<li class="logo"><a href=""><img src="../images/logo1.png"/></a></li>
					<li class="code"><img src="../images/code.jpg"/><p class="center">扫描关注微信</p></li>
					<li class="third"><img class="fl" src="../images/tell.png"/><p class="tell">88888888</p><p class="time">周一至周日 9:00-18:00</p></li>
				</ul>

			</div>
			<p class="line"></p>
			<div class="wp clear">
                <span class="fl">? 2012 www.atguigu.com谷粒教育-在线学习交流平台 保留所有权利</span>
                <span class="fr">copyright ? 2012 ICP备案证书号：蜀ICP备xxxxx号-1</span>
			</div>
		</div>
	</footer>

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>

{% block bottomfile %}
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}"  type="text/javascript"></script>
<script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{% endblock %}

{% block script %}

{% endblock %}
</body>
</html>

OES/oes/templates/forgetpwd.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>谷粒教育首页</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
<!--提示弹出框-->
<div class="successbox dialogbox" id="jsSuccessTips">
    <h1>成功提交</h1>
    <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
    <div class="cont">
        <h2>您的需求提交成功！</h2>
        <p></p>
    </div>
</div>
<div class="resetpassbox dialogbox" id="jsSetNewPwd">
    <h1>重新设置密码</h1>
    <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
    <p class="green">请输入新密码</p>
    <form id="jsSetNewPwdForm">
        <div class="box">
            <span class="word2">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</span>
            <input type="password" name="password" id="jsResetPwd" placeholder="请输入新密码"/>
        </div>
        <div class="box">
            <span class="word2">确&nbsp;认&nbsp;密&nbsp;码</span>
            <input type="password" name="password2" id="jsResetPwd2" placeholder="请再次输入新密码"/>
        </div>
        <div class="box">
            <span class="word2">验&nbsp;&nbsp;证&nbsp;&nbsp;码</span>
            <input type="text" name="code" id="jsResetCode" placeholder="请输入手机验证码"/>
        </div>
        <div class="error btns" id="jsSetNewPwdTips"></div>
        <div class="button">
            <input type="hidden" name="mobile" id="jsInpResetMobil" />
            <input id="jsSetNewPwdBtn" type="button" value="提交" />
        </div>
    </form>
</div>
<div class="bg" id="dialogBg"></div>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">谷粒教育，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>88888888</span></li>
                <li><a href="{% url 'users:login' %}">[登录]</a></li>
                <li class="active"><a href="/forgetpwd/">[忘记密码]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="index.html"></a>
                <h1>忘记密码</h1>
                <a class="index-font" href="index.html">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">
                        <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}" /></a></li>
                        <li><a href=""><img width="483" height="472" src="{% static 'images/mongoDB.jpg' %}" /></a></li>
                        <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}" /></a></li>
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <h2>忘记密码</h2>
                <form id="jsFindPwdForm" method="post" action="" autocomplete="off">
                    {% csrf_token %}
                    <div class="form-group marb20 ">
                        <label>帐&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;号</label>
                        <input type="text" id="account" name="email" value="None" placeholder="邮箱" />
                    </div>
                    <div class="form-group captcha1 marb38">
                        <label>验&nbsp;证&nbsp;码</label>
                        {{captcha.captcha}}
                    </div>
                    <div class="error btns" id="jsForgetTips">{{ msg }}</div>
                    <input type="hidden" name="sms_type" value="1">
                    <input class="btn btn-green" id="jsFindPwdBtn" type="submit" value="提交" />
                    <p class="form-p" style="bottom:40px;">您还可以<a href="login.html"> [直接登录]</a></p>
                </form>
            </div>
        </div>
    </div>
</section>

<input id="isLogin" type="hidden" value="False"/>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/login.js' %}"  type="text/javascript"></script>
</body>
</html>

OES/oes/templates/index.html
{% extends 'base.html' %}
{% load static %}



{% block content %}


    <div class="banner">
			<div class="wp">
				<div class="fl">
					<div class="imgslide">
						<ul class="imgs">

                            {% for slide in slides %}
                            <li>
                                    <a href="{{slide.url}}">
                                        <img width="1200" height="478" src="/static/media/{{slide.image}}" />
                                    </a>
                                </li>
                            {% endfor %}
						</ul>
					</div>
					<div class="unslider-arrow prev"></div>
					<div class="unslider-arrow next"></div>
				</div>

				</div>


			</div>
<!--banner end-->
<!--feature start-->
	<section>
		<div class="wp">
			<ul class="feature">
				<li class="feature1">
					<img class="pic" src="{% static 'images/feature5.png' %}"/>
					<p class="center">专业权威</p>
				</li>
				<li class="feature2">
					<img class="pic" src="{% static 'images/feature5.png' %}"/>
					<p class="center">课程最新</p>
				</li>
				<li class="feature3">
					<img class="pic" src="{% static 'images/feature5.png' %}"/>
					<p class="center">名师授课</p>
				</li>
				<li class="feature4">
					<img class="pic" src="{% static 'images/feature5.png' %}"/>
					<p class="center">数据真实</p>
				</li>
			</ul>
		</div>
	</section>
<!--feature end-->
<!--module1 start-->
	<section>
		<div class="module">
			<div class="wp">
				<h1>公开课程</h1>
				<div class="module1 eachmod">
					<div class="module1_1 left">
						<img width="228" height="614" src="{% static 'images/module5_1.jpg' %}"/>
						<p class="fisrt_word">名师授课<br/>专业权威</p>
						<a class="more" href="course-list.html">查看更多课程 ></a>
					</div>
					<div class="right group_list">
						<div class="module1_2 box">
							<div class="imgslide2">
								<ul class="imgs">
                                    {% for slide in slides_bottom %}
                                    <li>
                                        <a href="">
                                            <img width="470" height="300" src="/static/media/{{slide.image}}" />
                                        </a>
                                    </li>
                                    {% endfor %}

								</ul>
							</div>
							<div class="unslider-arrow2 prev"></div>
							<div class="unslider-arrow2 next"></div>
						</div>
                            {% for course in course_list %}
                            <div class="module1_{{forloop.counter|add:2}} box">
                                <a href="{% url 'course:coursedetail' course.id %}">
                                    <img width="233" height="190" src="/static/media/{{course.image}}"/>
                                </a>
                                <div class="des">
                                    <a href="course-detail.html">
                                        <h2 title="django入门">{{course.name}}</h2>
                                    </a>
                                    <span class="fl">难度：<i class="key">{% if course.grade == 1 %}初级{% elif course.grade == 2 %}中级{% else %}高级{% endif %}</i></span>
                                    <span class="fr">学习人数：{{course.learn_num}}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl" title="谷粒教育网">{{course.teacher.organization.name}}</span>
                                    <span class="star fr">{{course.fav_num}}</span>
                                </div>
                            </div>
                            {% endfor %}

					</div>
				</div>
			</div>
		</div>
	</section>
	<section>
		<div class="module greybg">
			<div class="wp">
				<h1>课程机构</h1>
				<div class="module3 eachmod">
					<div class="module3_1 left">
						<img width="228" height="463" src="{% static 'images/module6_1.jpg' %}"/>
						<p class="fisrt_word">名校来袭<br/>权威认证</p>
						<a class="more" href="org-list.html">查看更多机构 ></a>
					</div>
					<div class="right">
						<ul>
                                {% for org in org_list %}
                                <li class="">
                                    <a href="{% url 'organization:organizationdetailpagehome' org.id %}">
                                        <div class="company">
                                            <img width="184" height="100" src="/static/media/{{org.image}}"/>
                                            <div class="score">
                                                <div class="circle">
                                                    <h2>全国知名</h2>
                                                </div>
                                            </div>
                                        </div>
                                        <p><span class="key" title="谷粒教育网">{{org.name}}</span></p>
                                    </a>
                                </li>
                                {% endfor %}

						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>

{% endblock %}

OES/oes/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>谷粒教育在线网登录</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">谷粒教育在线网，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>88888888</span></li>
                <li class="active"><a href="{% url 'users:login' %}">[登录]</a></li>
                <li><a href="{% url 'users:register' %}">[注册]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="index.html"></a>
                <h1>用户登录</h1>
                <a class="index-font" href="{% url 'index:index' %}">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">
                            <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}" /></a></li>
                            <li><a href=""><img width="483" height="472" src="{% static 'images/mongoDB.jpg' %}" /></a></li>
                            <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}" /></a></li>
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <h2>帐号登录</h2>
                <form action="" method="post" autocomplete="off">
                    {% csrf_token %}
                    <div class="form-group marb20 ">
                        <label>用&nbsp;户&nbsp;名</label>
                        <input name="username" id="account_l" type="text" placeholder="手机号/邮箱" />
                    </div>
                    <div class="form-group marb8 ">
                        <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                        <input name="password" id="password_l" type="password" placeholder="请输入您的密码" />
                    </div>
                    <div class="error btns login-form-tips" id="jsLoginTips">{{ msg }}</div>
                     <div class="auto-box marb38">

                        <a class="fr" href="forgetpwd.html">忘记密码？</a>
                     </div>
                     <input class="btn btn-green" id="jsLoginBtn" type="submit" value="立即登录 > " />
                </form>
                <p class="form-p">没有谷粒教育在线网帐号？<a href="{% url 'users:register' %}">[立即注册]</a></p>
            </div>
        </div>
    </div>
</section>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/login.js' %}"  type="text/javascript"></script>
</body>
</html>

OES/oes/templates/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title>谷粒教育密码修改</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/css/style.css">

<body>
<div class="wp">
    <div class="resetpassword" id="resetPwdForm">
        <h1>修改密码</h1>
        <p>已经通过验证，请设置新密码</p>
        <form id="reset_password_form" action="" method="post">
            <ul>
                <li>
                    <span class="">新 密 码 ：</span>
                    <input type="password" name="password" id="pwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <li>
                    <span class="">确定密码：</span>
                    <input type="password" name="password2" id="repwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <li>
                    <span class="">验证码：</span>
                    <input type="password" name="password2" id="repwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <li class="button">
                    <input type="button" value="提交" onclick="reset_password_form_submit()">
                </li>
            </ul>
        </form>
    </div>
    <div class="resetpassword" id="reset_password_tips" style="display:none;">
        <h1>修改密码成功,请重新登录</h1>
        <img class="fl" src="/static/images/check2.png">
        <p class="successword">已经成功修改密码，请重新登录</p>
    </div>
</div>
</body>
</html>

OES/oes/templates/register.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
    <title>谷粒教育注册</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

</head>
<body>

<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">谷粒教育，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>88888888</span></li>
                <li><a href="{% url 'users:login' %}">[登录]</a></li>
                <li class="active"><a href="{% url 'users:register' %}">[注册]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="index.html"></a>
                <h1>用户注册</h1>
                <a class="index-font" href="{% url 'index:index' %}">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">

                        <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}" /></a></li>

                        <li><a href=""><img width="483" height="472" src="{% static 'images/mongoDB.jpg' %}" /></a></li>

                        <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}" /></a></li>

                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <div class="tab">
                    <h2>邮箱注册</h2>
                </div>
                
                <div class="tab-form">
                    <form id="email_register_form" method="post" action="" autocomplete="off">
                        {% csrf_token %}
                        <div class="form-group marb20 ">
                            <label>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱</label>
                            <input  type="text" id="id_email" name="email" value="None" placeholder="请输入您的邮箱地址" />
                        </div>
                        <div class="form-group marb8 ">
                            <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                            <input type="password" id="id_password" name="password"  value="None" placeholder="请输入6-20位非中文字符密码" />
                        </div>
                        <div class="form-group marb8 captcha1 ">
                            {{ registerform.captcha }}
                        </div>
                        <div class="error btns" id="jsEmailTips">{{ msg }}</div>
                        <div class="auto-box marb8">
                        </div>
                        <input class="btn btn-green" id="jsEmailRegBtn" type="submit" value="注册并登录" />
                    </form>
                </div>
                <p class="form-p">已有账号？<a href="{% url 'users:login' %}">[立即登录]</a></p>
            </div>
        </div>
    </div>
</section>

<input id="isLogin" type="hidden" value="False"/>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/login.js' %}"  type="text/javascript"></script>
</body>
</html>