OES/oes/courses/urls.py
from django.urls import path
from . import views
from haystack.views import SearchView
urlpatterns=[
    path('courselist/',views.CourseList,name='courselist'),
    path('coursedetail/<int:course_id>/',views.CourseDetail,name='coursedetail'),
    path('coursechapter/<int:course_id>/',views.CourseChapter,name='coursechapter'),
    path('video/<int:video_id>/',views.VideoOpen,name='video'),
    # path('search/', SearchView(), name='haystack_search'),

]

OES/oes/index/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.index,name='index'),
]

OES/oes/oes/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include(('users.urls','users'),namespace='users')),
    path('captcha/', include('captcha.urls')),
    path('', include(('index.urls', 'index'), namespace='index')),
    path('course/',include(('courses.urls','course'),namespace='course')),
    path('organization/',include(('organizations.urls','organization'),namespace='organization')),
    path('operation/', include(('operations.urls', 'operation'), namespace='operation')),
    # path('haystack/',include('haystack.urls'))

]

OES/oes/organizations/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('teacherlist/',views.TeacherList,name='teacherlist'),
    path('teacherdetail/<int:teacher_id>',views.TeacherDetail,name='teacherdetail'),
    path('organizationlist/',views.OrganizationList,name='organizationlist'),
    path('organizationdetailcourse/<int:org_id>',views.OrganizationDetailCourse,name='organizationdetailcourse'),
    path('organizationdetailpagehome/<int:org_id>', views.OrganizationDetailPagehome, name='organizationdetailpagehome'),
    path('organizationdetaildesc/<int:org_id>', views.OrganizationDetailDes, name='organizationdetaildesc'),
    path('organizationdetailteacher/<int:org_id>', views.OrganizationDetailTeacher, name='organizationdetailteacher'),
]

OES/oes/users/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('register/',views.UserRegister,name='register'),
    path('login/',views.UserLogin,name='login'),
    path('active_acount/<int:user_id>',views.Active_Acount,name='active_acount'),
    path('forgetpwd/',views.ForgetPwd,name='forgetpwd'),
    path('usercenterinfo/', views.UserCenterInfo, name='usercenterinfo'),
    path('userfavcourse/', views.UserFavCourse, name='userfavcourse'),
    path('userfavteacher/', views.UserFavTeacher, name='userfavteacher'),
    path('userfavorg/', views.UserFavOrg, name='userfavorg'),
    path('usermymsg/', views.MyMsg, name='usermymsg'),
    path('usermycourse/', views.MyCourse, name='usermycourse'),
    path('userlogout/', views.UserLogout, name='userlogout'),
    path('update/pwd/', views.ResetPwd, name='resetpwd'),
    path('image/upload/', views.UploadHeader, name='uploadheader'),
]

OES/oes/organizations/models.py
from django.db import models
from  basetables.base import BaseModel
# Create your models here.
# from courses.models import Course
class OrganizationCategory(BaseModel):
    name = models.CharField(verbose_name='机构类别',max_length=20)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '机构类别'
        verbose_name_plural = verbose_name

class City(BaseModel):
    city = models.CharField(verbose_name='城市',max_length=20)

    def __str__(self):
        return self.city

    class Meta:
        verbose_name = '城市'
        verbose_name_plural = verbose_name

class Organization(BaseModel):
    name = models.CharField(verbose_name='机构名字',max_length=20)
    image = models.ImageField(verbose_name='机构图片',max_length=200,upload_to='organization/%y/%m/%d/')
    organizationcategory = models.ForeignKey(OrganizationCategory,verbose_name='机构类别',on_delete=models.CASCADE)
    city = models.ForeignKey(City,verbose_name='城市',on_delete=models.CASCADE)
    teacher_num = models.IntegerField(default=0,verbose_name='教师数量')
    course_num = models.IntegerField(default=0,verbose_name='课程数目')
    learn_num = models.IntegerField(default=0,verbose_name='学习人数')
    detail_addr = models.CharField(max_length=200,verbose_name='详细地址',blank=True,null=True)
    introduce = models.TextField(verbose_name='机构介绍')
    recommend_num = models.IntegerField(verbose_name='推荐指数')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '机构'
        verbose_name_plural = verbose_name

class Teacher(BaseModel):
    name = models.CharField(verbose_name='教师名字',max_length=20)
    image = models.ImageField(upload_to='teacher/%y/%m/%d',verbose_name='头像')
    work_time = models.IntegerField(verbose_name='工作年数',default=0)
    organization = models.ForeignKey(Organization,verbose_name='所在公司',on_delete=models.CASCADE)
    age = models.IntegerField(verbose_name='年龄',default=0)
    postion = models.CharField(verbose_name='职位',max_length=20,blank=True,null=True)
    characteristic = models.CharField(verbose_name='教学特色',max_length=20,blank=True,null=True)
    course_num = models.IntegerField(default=0,verbose_name='课程数')
    learn_num = models.IntegerField(default=0,verbose_name='学习人数')
    gender = models.BooleanField(verbose_name='性别',choices=((True,'男'),(False,'女')),default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '教师'
        verbose_name_plural = verbose_name




# class GoodCourse(BaseModel):
#     course = models.ForeignKey(courses.Course,verbose_name='课程',on_delete=models.CASCADE)
#     organization = models.ForeignKey(Organization,verbose_name='机构',on_delete=models.CASCADE)

OES/oes/organizations/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Teacher,Organization,OrganizationCategory,City
# Create your views here.
from courses.models import Course
from django.core.paginator import Paginator
def TeacherList(request):
    page = request.GET.get('page',1)
    try:
        page = int(page)
    except:
        return HttpResponse('页码错误')
    teacher_list = Teacher.objects.all()
    p = Paginator(teacher_list,1)
    if p.num_pages<page:
        page = p.num_pages
    if page < 1:
        page = 1

    nextpage = 0
    last = 0
    if page-2 >0 and page+2 <= p.num_pages:
        nextpage = page+1
        last = page-1
        page_list = [page-2,page-1,page,page+1,page+2]
        print(page_list)
    elif page-2 <= 0 and page+2 >= p.num_pages:
        page_list = [x for x in range(1,p.num_pages+1)]
    elif page-2 <= 0 and page+ 2 < p.num_pages:
        page_list = [x for x in range(1,page+3)]
        nextpage = page+1
    else:
        page_list = [x for x in range(page-2,p.num_pages+1)]
        last = page-1

    teacher_list = p.page(page).object_list
    hotteacher_list = Teacher.objects.all().order_by('learn_num')[:5]
    context={
        'teacher_list':teacher_list,
        'flag': 'teacher',
        'hotteacher_list':hotteacher_list,

        'next': nextpage,
        'last': last,
        'page_list': page_list,
        'page': page,
    }
    return render(request,'organization/teachers-list.html',context=context)


def TeacherDetail(request,teacher_id):
    teacher=Teacher.objects.filter(id=teacher_id)
    if not teacher:
        return HttpResponse('不存在这个老师')
    teacher=teacher[0]
    course_list = Course.objects.filter(teacher=teacher)
    context={
        'teacher':teacher,
        'course_list':course_list,
    }

    return render(request,'organization/teacher-detail.html',context=context)


def OrganizationList(request):
    city = request.GET.get('city',False)
    ct = request.GET.get('ct',False)
    sort = request.GET.get('sort',False)
    if not any([city,ct,sort]):       #表示没有指定  查询全部
        organization_list = Organization.objects.all()
    elif city:                  #表示指定city
        organization_list = Organization.objects.filter(city=city)
    elif ct:
        #得到类别
        type_org=OrganizationCategory.objects.filter(id=ct)[0]
        organization_list = Organization.objects.filter(organizationcategory=type_org)
    else:
        organization_list = Organization.objects.all().order_by(sort)


    page = request.GET.get('page',1)
    try:
        page = int(page)
    except:
        return HttpResponse('页码错误')
    teacher_list = Teacher.objects.all()
    p = Paginator(teacher_list,1)
    if p.num_pages<page:
        page = p.num_pages
    if page < 1:
        page = 1

    nextpage = 0
    last = 0
    if page-2 >0 and page+2 <= p.num_pages:
        nextpage = page+1
        last = page-1
        page_list = [page-2,page-1,page,page+1,page+2]
        print(page_list)
    elif page-2 <= 0 and page+2 >= p.num_pages:
        page_list = [x for x in range(1,p.num_pages+1)]
    elif page-2 <= 0 and page+ 2 < p.num_pages:
        page_list = [x for x in range(1,page+3)]
        nextpage = page+1
    else:
        page_list = [x for x in range(page-2,p.num_pages+1)]
        last = page-1

    organization_list = p.page(page).object_list
    #根据机构的学习数来排名
    hotorganization_list = Organization.objects.all().order_by('learn_num')[:3]
    typelist = OrganizationCategory.objects.all()
    citylist = City.objects.all()
    context={
        'organization_list':organization_list,
        'typelist':typelist,
        'citylist':citylist,
        'flag': 'organization',
        'hotorg_list':hotorganization_list,

        'next': nextpage,
        'last': last,
        'page_list': page_list,
        'page': page,
    }
    return render(request,'organization/org-list.html',context=context)


def OrganizationDetailCourse(request,org_id):
    org = Organization.objects.filter(id=org_id)
    if not org:
        return HttpResponse('不存在机构')
    teachers = Teacher.objects.filter(organization=org_id)        #得到一个机构的所有的老师
    course_list=[]
    for teacher in teachers:
        courses=Course.objects.filter(teacher=teacher)
        course_list.extend(courses)
    context={
        'course_list':course_list,
        'org_id': org_id,
    }
    return render(request,'organization/org-detail-course.html',context=context)



def OrganizationDetailPagehome(request,org_id):
    org = Organization.objects.filter(id=org_id)
    if not org:
        return HttpResponse('不存在机构')
    org=org[0]
    teachers = Teacher.objects.filter(organization=org_id)        #得到一个机构的所有的老师
    course_list=[]
    for teacher in teachers:
        courses=Course.objects.filter(teacher=teacher)
        course_list.extend(courses)
    context={
        'course_list':course_list[:4],
        'teachers':teachers[:3],
        'org':org,
        'org_id':org_id,
    }
    return render(request,'organization/org-detail-homepage.html',context=context)




def OrganizationDetailDes(request,org_id):
    orgs = Organization.objects.filter(id=org_id)
    if not orgs:
        return HttpResponse('机构不存在')

    org=orgs[0]
    context={
        'org_id':org_id,
        'introduce':org.introduce,
    }
    return render(request,'organization/org-detail-desc.html',context=context)


def OrganizationDetailTeacher(request,org_id):
    orgs = Organization.objects.filter(id=org_id)
    if not orgs:
        return HttpResponse('机构不存在')
    org = orgs[0]
    teacher_list = Teacher.objects.filter(organization=org)
    context={
        'org_id':org_id,
        'teacher_list':teacher_list,
    }
    return render(request,'organization/org-detail-teachers.html',context=context)

OES/oes/templates/organization/org-detail-course.html
{% extends 'organization/orgbase.html' %}
{% load static %}
{% block title %}机构课程列表页{% endblock %}

{% block content %}
<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="index.html">首页</a>></li>
			<li><a href="org-list.html">课程机构</a>></li>
			<li>机构课程</li>
		</ul>
	</div>
</section>

<section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
                <li class=""><a href="{% url 'organization:organizationdetailpagehome' org_id %}">机构首页</a></li>
                <li class="active2"><a href="{% url 'organization:organizationdetailcourse' org_id %}">机构课程</a></li>
                <li class=""><a href="{% url 'organization:organizationdetaildesc' org_id %}">机构介绍</a></li>
                <li class=""><a href="{% url 'organization:organizationdetailteacher' org_id %}">机构讲师</a></li>

			</ul>
		</div>
    
<div class="right companycenter layout" >
		<div class="head">
			<h1>机构课程</h1>
		</div>
		<div class="brief group_list">

                {% for course in course_list %}
                    <div class="module1_5 box">
                    <a class="comp-img-box" href="course-detail.html">

                        <img width="214" height="195" src="/static/media/{{course.image}}"/>
                    </a>
                    <div class="des">
                        <a href="course-detail.html"><h2>{{course.name}}</h2></a>
                        <span class="fl">课时：<i class="key">{{course.time}}</i></span>
                        <span class="fr">学习人数：{{course.learn_num}}</span>
                    </div>
                    <div class="bottom">
                        <span class="fl">{{course.teacher.organization.name}}</span>
                         <span class="star fr  notlogin
                            " data-favid="13" data-fav-type="4">
                            {{course.fav_num}}
                        </span>
                    </div>
                </div>
                {% endfor %}
            

		</div>
			<div class="pageturn">
                <ul class="pagelist">
                    <li class="active"><a href="?page=1">1</a></li>
                </ul>
            </div>
	</div>


</section>
{% endblock %}

OES/oes/templates/organization/org-detail-teachers.html
{% extends 'organization/orgbase.html' %}
{% load static %}
{% block title %}谷粒教育网教师列表 - 谷粒教育网{%endblock %}

{% block content %}
<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="index.html">首页</a>></li>
			<li><a href="org-list.html">课程机构</a>></li>
			<li>机构教师</li>
		</ul>
	</div>
</section>

<section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
                <li class=""><a href="{% url 'organization:organizationdetailpagehome' org_id %}">机构首页</a></li>
                <li class=""><a href="{% url 'organization:organizationdetailcourse' org_id %}">机构课程</a></li>
                <li class=""><a href="{% url 'organization:organizationdetaildesc' org_id %}">机构介绍</a></li>
                <li class="active2"><a href="{% url 'organization:organizationdetailteacher' org_id %}">机构讲师</a></li>
			</ul>
		</div>
    
<div class="right companycenter layout" >
        <div class="head">
            <h1>机构讲师</h1>
        </div>
        <div class="messagelist">
            <div class=" butler_list butler-fav-box">

                {% for teacher in teacher_list %}
                <dl class="des users">
                    <dt>
                        <a href="{% url 'organization:teacherdetail' teacher.id %}">
                        <img width="100" height="100" class="scrollLoading" data-url="/static/media/{{teacher.image}}" src="/static/media/{{teacher.image}}"/>
                        </a>
                    </dt>
                    <dd>
                        <h1>
                            <a href="">
                            {{teacher.name}}<span class="key">已认证</span>
                            </a>
                        </h1>
                        <ul class="cont clearfix">
                            <li class="time">工作年限：<span>{{teacher.time}}年</span></li>
                            <li class="c7">课程数：<span>{{teacher.course_num}}</span></li>
                        </ul>
                    </dd>
                </dl>
                {% endfor %}
                

            </div>
        </div>
    </div>

    </div>
</section>

{% endblock %}

{% block script %}
<script type="text/javascript">
    //收藏分享
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "GET",
        url:"/operation/add_fav/",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "5I2SlleZJOMUX9QbwYLUIAOshdrdpRcy");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="login.html";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$('.collectionbtn').on('click', function(){

    add_fav($(this), 1, 2);
});

$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path		: '../images/',
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg  : '暂时还未获得评价！',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);

    $('.jsFavBtn').on('click', function(){
        var type = $(this).attr('data-fav-type');
        if(type == '1'){
            favPraise($(this), 'fav' ,1 , '收藏');

        }else if(type == '3'){
            favPraise($(this), 'fav' ,3 );

        }else if(type == '11'){
            favPraise($(this), 'pra', 1);

        }else if(type == '4'){
            favPraise($(this), 'fav' ,4 );

        }
    });
})
</script>


<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });

    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>
{% endblock %}

OES/oes/templates/organization/orgbase.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}机构课程列表页{% endblock %}</title>

    {% block topfile %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">

    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

    {% endblock %}

</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header2 header">

 			<div class="top">
				<div class="wp">
					<div class="fl"><p>服务电话：<b>8888888</b></p></div>
					<!--登录后跳转-->

                        {% if not request.user.is_authenticated %}
                         <a style="color:white" class="fr registerbtn" href="{% url 'users:register' %}">注册</a>
                         <a style="color:white" class="fr loginbtn" href="{% url 'users:login' %}">登录</a>
						{% else %}
						<div class="personal">
                            <dl class="user fr">
                                <dd>{{ request.user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{{request.user.image}}"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="{{request.user.image}}"/></dt>
	                                <dd>
	                                    <h2>django</h2>
	                                    <p>{{ request.user.username }}</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="{% url 'users:usercenterinfo' %}">进入个人中心</a>
	                                <a class="fr" href="{% url 'users:userlogout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                        {% endif %}

				</div>
			</div>


    <div class="middle companyheader">
        <div class="wp">
            <a href="{% url 'index:index' %}">
            <img class="fl" style="width: 112px;height: 103px" src="{% static 'images/org.png' %}"/>
            </a>
            <div class="head fl">
                <h1>

                    谷粒教育网
                    <img src="{% static 'images/authentication.png' %}"/>
                    <img src="{% static 'images/gold.png' %}"/>
                </h1>
                <p class="fl">
                    <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                    <span class="precision company-credit" data-star-scope="5.0"></span>
                    <span class="key">5</span>
                </p>
            </div>
            <div class="btn fr collectionbtn  notlogin
                 "data-favid="{{org_id}}" data-fav-type="3">
                 收藏
            </div>

        </div>
    </div>
			</div>
    </header>
</section>


{% block content %}
{% endblock %}

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>



{% block bottomfile %}
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js" type="text/javascript' %}"></script>

<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>

{% endblock %}

{% block script %}
<script type="text/javascript">
    //收藏分享
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"/operation/add_fav/",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "5I2SlleZJOMUX9QbwYLUIAOshdrdpRcy");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="login.html";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$('.collectionbtn').on('click', function(){
    fav_id = $('.collectionbtn').attr('data-favid');
    type_id = $('.collectionbtn').attr('data-fav-type');
    add_fav($(this),  fav_id, type_id);
});

$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path		: '{% static 'images/',
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg  : '暂时还未获得评价！',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);

    $('.jsFavBtn').on('click', function(){
        var type = $(this).attr('data-fav-type');
        if(type == '1'){
            favPraise($(this), 'fav' ,1 , '收藏');

        }else if(type == '3'){
            favPraise($(this), 'fav' ,3 );

        }else if(type == '11'){
            favPraise($(this), 'pra', 1);

        }else if(type == '4'){
            favPraise($(this), 'fav' ,4 );

        }
    });
})
</script>


<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });

    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>
{% endblock %}
</body>
</html>